// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/provisioning-service/proto/restartaz/restartaz.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_service_provisioning_restartaz is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/provisioning-service/proto/restartaz/restartaz.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_service_provisioning_restartaz

import proto "github.com/HailoOSS/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Request struct {
	AzName           *string `protobuf:"bytes,1,req,name=azName" json:"azName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetAzName() string {
	if m != nil && m.AzName != nil {
		return *m.AzName
	}
	return ""
}

type Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func init() {
}
