// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/provisioning-service/proto/event.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_provisioning is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/provisioning-service/proto/event.proto

It has these top-level messages:
	Event
*/
package com_HailoOSS_kernel_provisioning

import proto "github.com/HailoOSS/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Event struct {
	ServiceName      *string `protobuf:"bytes,1,req,name=serviceName" json:"serviceName,omitempty"`
	ServiceVersion   *uint64 `protobuf:"varint,2,req,name=serviceVersion" json:"serviceVersion,omitempty"`
	MachineClass     *string `protobuf:"bytes,3,req,name=machineClass" json:"machineClass,omitempty"`
	Hostname         *string `protobuf:"bytes,4,req,name=hostname" json:"hostname,omitempty"`
	AzName           *string `protobuf:"bytes,5,req,name=azName" json:"azName,omitempty"`
	Action           *string `protobuf:"bytes,6,req,name=action" json:"action,omitempty"`
	Info             *string `protobuf:"bytes,7,req,name=info" json:"info,omitempty"`
	Timestamp        *int64  `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *Event) GetServiceVersion() uint64 {
	if m != nil && m.ServiceVersion != nil {
		return *m.ServiceVersion
	}
	return 0
}

func (m *Event) GetMachineClass() string {
	if m != nil && m.MachineClass != nil {
		return *m.MachineClass
	}
	return ""
}

func (m *Event) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *Event) GetAzName() string {
	if m != nil && m.AzName != nil {
		return *m.AzName
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Event) GetInfo() string {
	if m != nil && m.Info != nil {
		return *m.Info
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
}
